dotfiles_source_local() {
    local file="${XDG_CONFIG_HOME:-$HOME/.config}/shell/local.sh"
    [[ -f $file ]] || return 0
    [[ -O $file ]] || { printf 'dotfiles: refusing non-owned %s\n' "$file" >&2; return 1; }
    local mode
    mode=$(stat -c '%a' "$file" 2>/dev/null || stat -f '%Lp' "$file" 2>/dev/null) || return 1
    (( (8#$mode & 0022) == 0 )) || { printf 'dotfiles: refusing writable %s\n' "$file" >&2; return 1; }
    # shellcheck source=/dev/null
    . "$file"
}

dotfiles_source_cache() {
    local tool=$1 shell=$2 cache="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/shell-init/$1.$2"
    [[ -r $cache ]] || return 0
    local header cached current
    IFS= read -r header < "$cache"
    cached=${header#* version=}
    if command -v "$tool" >/dev/null 2>&1; then
        current=$("$tool" --version 2>/dev/null | head -1)
        if [[ $header == '# generated by dotfiles;'* && $cached != "$current" ]]; then
            printf 'dotfiles: %s init cache is stale; run ./setup.sh module update %s\n' "$tool" "$tool" >&2
            return 0
        fi
    fi
    # shellcheck source=/dev/null
    . "$cache"
}
