proxy_on() {
    local proxy_url="${1:-${DOTFILES_PROXY_URL:-http://127.0.0.1:7897}}"
    local bypass_list="${DOTFILES_NO_PROXY:-localhost,127.0.0.1,::1}"

    case "$proxy_url" in
        http://*|https://*|socks4://*|socks5://*|socks5h://*) ;;
        *)
            printf 'dotfiles: unsupported proxy URL scheme\n' >&2
            return 2
            ;;
    esac

    export HTTP_PROXY="$proxy_url" HTTPS_PROXY="$proxy_url" ALL_PROXY="$proxy_url"
    export http_proxy="$proxy_url" https_proxy="$proxy_url" all_proxy="$proxy_url"
    export NO_PROXY="$bypass_list" no_proxy="$bypass_list"
    printf 'proxy on\n'
}

proxy_off() {
    unset HTTP_PROXY HTTPS_PROXY ALL_PROXY
    unset http_proxy https_proxy all_proxy
    unset NO_PROXY no_proxy
    printf 'proxy off\n'
}

dotfiles_source_local() {
    local file="${XDG_CONFIG_HOME:-$HOME/.config}/shell/local.sh"
    [[ -f $file ]] || return 0
    [[ -O $file ]] || { printf 'dotfiles: refusing non-owned %s\n' "$file" >&2; return 1; }
    local mode
    mode=$(stat -c '%a' "$file" 2>/dev/null || stat -f '%Lp' "$file" 2>/dev/null) || return 1
    (( (8#$mode & 0022) == 0 )) || { printf 'dotfiles: refusing writable %s\n' "$file" >&2; return 1; }
    # shellcheck source=/dev/null
    . "$file"
}

dotfiles_source_cache() {
    local tool=$1 shell=$2 cache="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/shell-init/$1.$2"
    [[ -r $cache ]] || return 0
    local header cached current
    IFS= read -r header < "$cache"
    cached=${header#* version=}
    if command -v "$tool" >/dev/null 2>&1; then
        current=$("$tool" --version 2>/dev/null | head -1)
        if [[ $header == '# generated by dotfiles;'* && $cached != "$current" ]]; then
            printf 'dotfiles: %s init cache is stale; run ./setup.sh module update %s\n' "$tool" "$tool" >&2
            return 0
        fi
    fi
    # shellcheck source=/dev/null
    . "$cache"
}
