#!/usr/bin/env bash
set -Eeuo pipefail
cache="$DOTFILES_CACHE_DIR/shell-init"
mkdir -p -- "$cache"
version=$(fzf --version | head -1)
for shell in bash zsh; do
    output="$cache/fzf.$shell"; tmp=$(mktemp "$output.XXXXXX")
    printf '# generated by dotfiles; tool=fzf version=%s\n' "$version" > "$tmp"
    if [[ $shell == bash ]]; then
        for file in /usr/share/doc/fzf/examples/completion.bash /usr/share/doc/fzf/examples/key-bindings.bash; do [[ ! -r $file ]] || cat "$file" >> "$tmp"; done
    else
        for file in /usr/share/doc/fzf/examples/completion.zsh /usr/share/doc/fzf/examples/key-bindings.zsh; do [[ ! -r $file ]] || cat "$file" >> "$tmp"; done
    fi
    mv -f -- "$tmp" "$output"
done
