#!/usr/bin/env bash
set -Eeuo pipefail
tool=${1:?tool required}
cache=${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/shell-init
mkdir -p -- "$cache"
generate() {
    local shell=$1 output=$2 tmp
    tmp=$(mktemp "$output.XXXXXX")
    {
        printf '# generated by dotfiles; tool=%s version=%s\n' "$tool" "$("$tool" --version 2>/dev/null | head -1)"
        case $tool in
            mise) "$tool" activate "$shell";;
            starship|zoxide) "$tool" init "$shell";;
        esac
    } > "$tmp"
    mv -f -- "$tmp" "$output"
}
case $tool in
    mise) generate bash "$cache/mise.bash"; generate zsh "$cache/mise.zsh";;
    starship) generate bash "$cache/starship.bash"; generate zsh "$cache/starship.zsh";;
    zoxide) generate bash "$cache/zoxide.bash"; generate zsh "$cache/zoxide.zsh";;
    *) printf 'unsupported init generator: %s\n' "$tool" >&2; exit 2;;
esac
